# #+bibliography: resume.bib
#+cite_export: biblatex

* Config/Preamble                                                  :noexport:
** LaTeX Config
#+BEGIN_SRC emacs-lisp :exports none  :results none :eval always
(require 'oc-biblatex)
(setq org-latex-with-hyperref nil) ;; stop org adding hypersetup{author..} to latex export

(setq org-latex-logfiles-extensions (quote ("lof" "lot" "tex~" "aux" "idx" "log" "out" "toc" "nav" "snm" "vrb" "dvi" "fdb_latexmk" "blg" "brf" "fls" "entoc" "ps" "spl" "bbl" "xmpi" "run.xml" "bcf")))

(add-to-list 'org-latex-classes
             '("altacv" "\\documentclass[10pt,a4paper,ragged2e,withhyper]{altacv}

% Change the page layout if you need to
\\geometry{left=1.25cm,right=1.25cm,top=1.5cm,bottom=1.5cm,columnsep=1.2cm}

% Use roboto and lato for fonts
\\renewcommand{\\familydefault}{\\sfdefault}

% Change the colours if you want to
\\definecolor{SlateGrey}{HTML}{2E2E2E}
\\definecolor{LightGrey}{HTML}{666666}
\\definecolor{DarkPastelRed}{HTML}{450808}
\\definecolor{PastelRed}{HTML}{8F0D0D}
\\definecolor{GoldenEarth}{HTML}{E7D192}
\\colorlet{name}{black}
\\colorlet{tagline}{PastelRed}
\\colorlet{heading}{DarkPastelRed}
\\colorlet{headingrule}{GoldenEarth}
\\colorlet{subheading}{PastelRed}
\\colorlet{accent}{PastelRed}
\\colorlet{emphasis}{SlateGrey}
\\colorlet{body}{LightGrey}

% Change some fonts, if necessary
\\renewcommand{\\namefont}{\\Huge\\rmfamily\\bfseries}
\\renewcommand{\\personalinfofont}{\\footnotesize}
\\renewcommand{\\cvsectionfont}{\\LARGE\\rmfamily\\bfseries}
\\renewcommand{\\cvsubsectionfont}{\\large\\bfseries}

% Change the bullets for itemize and rating marker
% for \cvskill if you want to
\\renewcommand{\\itemmarker}{{\\small\\textbullet}}
\\renewcommand{\\ratingmarker}{\\faCircle}
"

               ("\\cvsection{%s}" . "\\cvsection*{%s}")
               ("\\cvevent{%s}" . "\\cvevent*{%s}")))
(setq org-latex-packages-alist 'nil)
(setq org-latex-default-packages-alist
      '(("rm" "roboto"  t)
        ("defaultsans" "lato" t)
        ("" "paracol" t)
        ))
(require 'ox-extra)
(ox-extras-activate '(latex-header-blocks ignore-headlines))
#+END_SRC
#+LATEX_CLASS: altacv
#+LATEX_HEADER: \columnratio{0.6} % Set the left/right column width ratio to 6:4.
#+LATEX_HEADER: \usepackage[bottom]{footmisc}
*** Bibliography
# #+LATEX_HEADER: \DeclareNameAlias{sortname}{last-first}
#+LATEX_HEADER: \DeclareNameAlias{sortname}{given-family}
#+LATEX_HEADER: \addbibresource{resume.bib}
# #+LATEX_HEADER: \usepackage[citestyle=numeric-comp, maxcitenames=1, maxbibnames=4, doi=false, isbn=false, eprint=true, backend=bibtex, hyperref=true, url=false, natbib=true]{biblatex}
# #+LATEX_HEADER: \usepackage[backend=biber, sorting=nyvt, style=authoryear, firstinits]{biblatex}
# #+LATEX_HEADER: \usepackage[backend=natbib, giveninits=true]{biblatex}
# #+LATEX_HEADER: \usepackage[style=trad-abbrv,sorting=none,sortcites=true,doi=false,url=false,giveninits=true,hyperref]{biblatex}

** Exporter Settings
#+AUTHOR: Harrison Pielke-Lombardo
#+EXPORT_FILE_NAME: ./resume.pdf
#+OPTIONS: toc:nil title:nil H:1
** Macros
#+MACRO: cvevent \cvevent{$1}{$2}{$3}{$4}
#+MACRO: cvachievement \cvachievement{$1}{$2}{$3}{$4}
#+MACRO: cvtag \cvtag{$1}
#+MACRO: divider \divider
#+MACRO: par-div \par\divider
#+MACRO: new-page \newpage
* CV Header :ignore:
** Photo & Tagline :ignore:
#+begin_export latex
\name{Harrison Pielke-Lombardo}
\photoR{2.8cm}{Harrison_2015s.jpg}
\tagline{PhD Researcher}
#+end_export

** Personal Info :ignore:
#+begin_export latex
\personalinfo{
 %%  \homepage{www.github.com/tuh8888}
  \email{harrison.pielke-lombardo@cuanschutz.edu}
  \phone{720 209 6249}
  \location{Denver, CO}
  \dob{12 May 1995}
  \github{tuh8888}
  \linkedin{tuh8888}
%%   \driving{US Driving Licence
  }
}
\makecvheader
#+end_export

* CV Column 1 :ignore:
#+begin_export latex
\begin{paracol}{2}
#+end_export
** Personal Statement General                               :ignore:
#+begin_export latex
 \begin{quote}
 ``I am a Computational Bioscience graduate interested in developing software for artificial intelligence, health informatics, and game development. My work has included developing novel algorithms for symbolic AI and natural language processing. I am a polyglot programmer who enjoys turning difficult problems for people into easy solutions for computers.''
 \end{quote}
#+end_export
** Personal Statement Reify Health                          :ignore:noexport:
#+begin_export latex
 \begin{quote}
 ``I am a Computational Bioscience graduate interested in developing software for healthcare, bioinformatics, and clinical applications. My work has included developing novel algorithms for symbolic AI and natural language processing. I am a polyglot programmer who enjoys turning difficult problems for people into easy solutions for computers.''
 \end{quote}
#+end_export
** Experience
*** PhD Researcher :ignore:
{{{cvevent(PhD Researcher, University of Colorado\, Anschutz Medical Campus, 2016 -- 2022, Aurora\, CO)}}}

- Thesis title: Schematization of biological mechanisms using network alignment and computational analogy for hypothesizing about disease mechanisms and their interventions.
- Managed ongoing projects for lab

{{{cvtag(Knowledge-bases)}}}
{{{cvtag(Artificial intelligence)}}}
{{{cvtag(Biomedical datascience)}}}

** Projects
*** LeSS                                                             :ignore:

    {{{cvevent(Least Subsuming Subgraph,,, 2019 -- 2022,)}}}

    - Compare knowledge graphs using structural, semantic, and causal properties.
    # - Extends analogical reasoning to allow for comparison and generalization.
    - Can be used for hypothesis generation, cross-disciplinary knowledge transfer, and contextualization of scientific findings

      # {{{cvtag(Artificial intelligence)}}}
      # {{{cvtag(Knowledge graphs)}}}
      # {{{cvtag(Algorithm development)}}}
      # {{{cvtag(Analogical reasoning)}}}

*** Knowtator                                                        :ignore:

{{{par-div}}}

{{{cvevent(Knowtator: Concept and relation annotation plugin for Protégé,, 2017 - Ongoing,)}}}

- User-oriented interactions between structured and unstructured data.
- Interop between ontology development and concept/relation annotation

# {{{cvtag(Semantic web)}}}
# {{{cvtag(UX/GUI)}}}
# {{{cvtag(Ontology)}}}

*** Dep2Rel                                                          :ignore:

{{{par-div}}}

{{{cvevent(Bootstrapped relation extraction using word embeddings and dependency paths,, 2017 -- 2019,)}}}

- Extracting drug-target interactions from full text articles.
- Creates human-interpretable syntax patterns from dependency paths encoded using word embeddings.
- Bootstrapped algorithm incorporating GPU accelerated matrix operations for scalability

# {{{cvtag(Natural language processing)}}}
# {{{cvtag(Semantic web)}}}

** Publications                                                    :noexport:
    #+begin_export latex
 \nocite{*}
 % \printbibliography[heading=pubtype,title={\printinfo{\faBook}{Books}},type=book]
 % \divider
 % \printbibliography[heading=pubtype,title={\printinfo{\faFile*[regular]}{Journal Articles}},type=article]
 % \divider
 \printbibliography[heading=none]
 #+end_export

** Newpage :ignore:
{{{new-page}}}

** Projects (Cont.)                                                :noexport:

** A day of my life :noexport:
# #+begin_export latex
# % \medskip

# % \cvsection{A Day of My Life}

# % % Adapted from @Jake's answer from http://tex.stackexchange.com/a/82729/226
# % % \wheelchart{outer radius}{inner radius}{
# % % comma-separated list of value/text width/color/detail}
# % \wheelchart{1.5cm}{0.5cm}{%
# %   6/8em/accent!30/{Sleep,\\beautiful sleep},
# %   3/8em/accent!40/Hopeful novelist by night,
# %   8/8em/accent!60/Daytime job,
# %   2/10em/accent/Sports and relaxation,
# %   5/6em/accent!20/Spending time with family
# % }

# % % use ONLY \newpage if you want to force a page break for
# % % ONLY the current column
# % \newpage
# #+end_export

** Newpage :ignore:noexport:
{{{new-page}}}

** Volunteering                                                    :noexport:
*** FARSCOPE Course Rep :ignore:
{{{cvevent(Cohort Representative, FARSCOPE CDT, Sept 2018 - Ongoing, Bristol\, UK)}}}
# - I represent myself and fellow CDT students in management meetings where I communicate ideas and information between students and management.
- Represent myself and my CDT peers in management meetings.
- Communicate information between students and management.

{{{cvtag(Communication)}}}
{{{cvtag(Interpersonal Skills)}}}

{{{par-div}}}

*** Code Club :ignore:
{{{cvevent(Club Leader, Code Club, Dec 2017 - April 2018, Junction 3 Library\, Bristol \, UK)}}}

# - I collaborated with [[https://codeclub.org/en/][Code Club]] and Bristol Libraries to set up and run a Code Club for young people aged 9-13.
# - Demonstrating my abi involved organising,  planning lessons and teaching
- Set up (and then ran) a [[https://codeclub.org/en/][Code Club]] for children aged 9-13.
- Led the organisation, planning and teaching of weekly lessons.
- Planned lessons to engage children by making coding fun.
- Extremely rewarding and reinforced my love for teaching.
# - @ Junction 3 Library in Easton, Bristol.

{{{cvtag(Leadership)}}}
{{{cvtag(Teaching)}}}
{{{cvtag(Communication)}}}
{{{cvtag(Active listening)}}}

*** Drivetrain :ignore:noexport:
{{{par-div}}}

{{{cvevent(Technical Lead (Drivetrain), Formula Student, Jan 2015 - Jan 2016, Bristol\, UK)}}}

Each year, as part of Formula Student, students design, build and race a single seat race car.
- Finished 2nd in the National Class 2 competition in 2013/2014, I was then selected as the Drivetrain lead.
- This role improved my communication skills as I was leading weekly presentations.
- I developed my leadership skills through setting realistic objectives, effectively allocating work to the appropriate team members and monitoring outcomes.

{{{cvtag(Teamwork)}}}
{{{cvtag(Leadership)}}}
{{{cvtag(Time Management)}}}

*** Snowboard Captain :ignore:noexport:
{{{par-div}}}

{{{cvevent(Snowboard Captain, University of Bristol Snowsports Club, Jan 2014 - Sept 2015, Bristol\, UK)}}}

- Organised multiple weekly training sessions, demonstrating my ability to plan and run events smoothly.
- Negotiated competitive prices for a growing member base within an inherently expensive sport.
- Responsible for aiding the smooth running of the club and helping to organise the annual university ski trip, with circa 1500 participants, working under pressure to manage people in high stress situations.
- Awarded the ‘Team of the Year’ award and full colours for my performances and contributions to the sport.

{{{cvtag(Teamwork)}}}
{{{cvtag(Leadership)}}}
{{{cvtag(Time Management)}}}

* CV Column 2                                                        :ignore:
# Switch to the right column - will automatically move to the next page.
#+begin_export latex
\switchcolumn
#+end_export

** Skills
*** \textcolor{accent}{Clojure(script) (6 years)}
    :PROPERTIES:
    :UNNUMBERED: t
    :END:
    \hfill \break
    {{{cvtag(Reagent)}}}
    {{{cvtag(Re-frame)}}}
    {{{cvtag(Rum)}}}
    \hfill \break
    {{{cvtag(Datascript/Datomic)}}}
*** \textcolor{accent}{Python (10 years)}
    :PROPERTIES:
    :UNNUMBERED: t
    :END:
\hfill \break
{{{cvtag(NumPy)}}}
{{{cvtag(Pandas)}}}
{{{cvtag(SciKitLearn)}}}
*** \textcolor{accent}{Data visualization}
    :PROPERTIES:
    :UNNUMBERED: t
    :END:
\hfill \break
{{{cvtag(Matplotlib)}}}
{{{cvtag(Vega/VegaLite)}}}
{{{cvtag(GraphViz)}}}
{{{cvtag(Jupyter(Lab))}}}
*** \textcolor{accent}{Additional languages}
    :PROPERTIES:
    :UNNUMBERED: t
    :END:
\hfill \break
{{{cvtag(Java)}}}
{{{cvtag(HTML/CSS)}}}
{{{cvtag(Common Lisp)}}}
{{{cvtag(Bash)}}}
{{{cvtag(C++)}}}
{{{cvtag(R)}}}
{{{cvtag(MATLAB)}}}
*** \textcolor{accent}{Development tools}
    :PROPERTIES:
    :UNNUMBERED: t
    :END:
\hfill \break
{{{cvtag(Linux)}}}
{{{cvtag(Git/GitHub)}}}
{{{cvtag(LaTeX)}}}
{{{cvtag(Org-mode)}}}
*** \textcolor{accent}{Areas of expertise}
    :PROPERTIES:
    :UNNUMBERED: t
    :END:
\hfill \break
{{{cvtag(NLP)}}}
{{{cvtag(ML/AI)}}}
{{{cvtag(Semantic web)}}}
# {{{cvtag(Artificial intelligence)}}}

** Education
{{{cvevent(PhD Candidate in Computational Biosciences, University of Colorado\, Anschutz Medical Campus, 2016 -- Ongoing, Aurora\, Co)}}}

{{{divider}}}

#+BEGIN_EXPORT latex
\cvevent{\footnote{Awarded if PhD is not completed.} MS in Biomedical Sciences}{University of Colorado\, Anschutz Medical Campus}{2016 --- 2022}{Aurora\, CO}
#+END_EXPORT

{{{divider}}}

{{{cvevent(BS in Applied Mathematics, University of Colorado, 2013 -- 2016,Boulder\, CO)}}}
# - First Class Honours \\

** Newpage :ignore:noexport:
#+BEGIN_EXPORT latex
\newpage
#+END_EXPORT

** My Life Philosophy :noexport:
#+begin_export latex
% \begin{quote}
% ``Something smart or heartfelt, preferably in one sentence.''
% \end{quote}
#+end_export

** Achievements :noexport:
{{{cvachievement(\faTrophy, Full Sporting Colours, Awarded full colours for outstanding achievements in snowboarding. Multiple gold medals in British University Snowboard Championships.)}}}

{{{divider}}}

{{{cvachievement(\faCertificate, Starting To Teach, Established myself as a confident\, enthusiastic and effective teacher who is able to engage\, encourage and develop students' learning.)}}}

{{{divider}}}

{{{cvachievement(\faTrophy,Bristol Plus Award, For undertaking a wide range of tasks to further enhance student skills - only 700 out of 23\,000 achieved this award per annum.)}}}

{{{divider}}}

{{{cvachievement(\faCertificate, Mary Jones Prize for Mathematics, For outstanding achievements in A Level mathematics @ Ripon Grammar School)}}}

{{{divider}}}

{{{cvachievement(\faTrophy, The Duke of Edinburgh's Award, Bronze/Silver/Gold)}}}

** Languages :noexport:
#+begin_export latex
% \cvsection{Languages}

% \cvskill{English}{5}
% \divider

% \cvskill{Spanish}{4}
% \divider

% \cvskill{German}{3}

% %% Yeah I didn't spend too much time making all the
% %% spacing consistent... sorry. Use \smallskip, \medskip,
% %% \bigskip, \vpsace etc to make ajustments.
% \medskip
#+end_export

\newpage
** References                                                      :noexport:
#+begin_export latex
% \cvref{name}{email}{mailing address}
\cvref{Dr.\ Lawrence Hunter}{University of Colorado}{lawrence.hunter@cuanschutz.edu}
% {Address Line 1\\Address line 2}
#+end_export
- Thesis advisor
{{{divider}}}
#+begin_export latex
\cvref{Dr.\ James Costello}{University of Colorado}{james.costello@cuanschutz.edu}
% {Address Line 1\\Address line 2}
#+end_export
- Committee chair

* Back Matter :ignore:
#+begin_export latex
\end{paracol}
\end{document}
#+end_export

# Local Variables:
# org-cite-global-bibliography: nil
# End:
