# -*- eval: (pdf-auto-export-mode); -*-
# #+bibliography: resume.bib
#+cite_export: biblatex

* Config/Preamble                                                  :noexport:
** LaTeX Config
   #+BEGIN_SRC emacs-lisp :exports none  :results none :eval always
(require 'oc-biblatex)
(setq org-latex-with-hyperref nil) ;; stop org adding hypersetup{author..} to latex export

(setq org-latex-logfiles-extensions (quote ("lof" "lot" "tex~" "aux" "idx" "log" "out" "toc" "nav" "snm" "vrb" "dvi" "fdb_latexmk" "blg" "brf" "fls" "entoc" "ps" "spl" "bbl" "xmpi" "run.xml" "bcf")))

(add-to-list 'org-latex-classes
             '("altacv" "\\documentclass[10pt,a4paper,ragged2e,withhyper]{altacv}

% Change the page layout if you need to
\\geometry{left=1.25cm,right=1.25cm,top=1.5cm,bottom=1.5cm,columnsep=1.2cm}

% Use roboto and lato for fonts
\\renewcommand{\\familydefault}{\\sfdefault}

% Change the colours if you want to
\\definecolor{SlateGrey}{HTML}{2E2E2E}
\\definecolor{LightGrey}{HTML}{666666}
\\definecolor{DarkPastelRed}{HTML}{450808}
\\definecolor{PastelRed}{HTML}{8F0D0D}
\\definecolor{GoldenEarth}{HTML}{E7D192}
\\colorlet{name}{black}
\\colorlet{tagline}{PastelRed}
\\colorlet{heading}{DarkPastelRed}
\\colorlet{headingrule}{GoldenEarth}
\\colorlet{subheading}{PastelRed}
\\colorlet{accent}{PastelRed}
\\colorlet{emphasis}{SlateGrey}
\\colorlet{body}{LightGrey}

% Change some fonts, if necessary
\\renewcommand{\\namefont}{\\Huge\\rmfamily\\bfseries}
\\renewcommand{\\personalinfofont}{\\footnotesize}
\\renewcommand{\\cvsectionfont}{\\LARGE\\rmfamily\\bfseries}
\\renewcommand{\\cvsubsectionfont}{\\large\\bfseries}

% Change the bullets for itemize and rating marker
% for \cvskill if you want to
\\renewcommand{\\itemmarker}{{\\small\\textbullet}}
\\renewcommand{\\ratingmarker}{\\faCircle}
"

               ("\\cvsection{%s}" . "\\cvsection*{%s}")
               ("\\cvevent{%s}" . "\\cvevent*{%s}")))
(setq org-latex-packages-alist 'nil)
(setq org-latex-default-packages-alist
      '(("rm" "roboto"  t)
        ("defaultsans" "lato" t)
        ("" "paracol" t)
        ))
(require 'ox-extra)
(ox-extras-activate '(latex-header-blocks ignore-headlines))
   #+END_SRC
   #+LATEX_CLASS: altacv
   #+LATEX_HEADER: \usepackage[bottom]{footmisc}
*** Bibliography
    # #+LATEX_HEADER: \DeclareNameAlias{sortname}{last-first}
    #+LATEX_HEADER: \DeclareNameAlias{sortname}{given-family}
    #+LATEX_HEADER: \addbibresource{resume.bib}
    # #+LATEX_HEADER: \usepackage[citestyle=numeric-comp, maxcitenames=1, maxbibnames=4, doi=false, isbn=false, eprint=true, backend=bibtex, hyperref=true, url=false, natbib=true]{biblatex}
    # #+LATEX_HEADER: \usepackage[backend=biber, sorting=nyvt, style=authoryear, firstinits]{biblatex}
    # #+LATEX_HEADER: \usepackage[backend=natbib, giveninits=true]{biblatex}
    # #+LATEX_HEADER: \usepackage[style=trad-abbrv,sorting=none,sortcites=true,doi=false,url=false,giveninits=true,hyperref]{biblatex}

** Exporter Settings
   #+AUTHOR: Harrison Pielke-Lombardo
   #+EXPORT_FILE_NAME: ./resume.pdf
   #+OPTIONS: toc:nil title:nil H:1
** Macros
   #+MACRO: cvevent \cvevent{$1}{$2}{$3}{$4}
   #+MACRO: cvachievement \cvachievement{$1}{$2}{$3}{$4}
   #+MACRO: cvtag  \cvtag{$1}
   #+MACRO: accent   \textcolor{accent}{$1}
   #+MACRO: divider \divider
   #+MACRO: par-div \par
   #+MACRO: new-page \newpage

* Header                                                             :ignore:

** Photo & Tagline :ignore:
   #+begin_export latex
   \name{Harrison Pielke-Lombardo}
   \photoR{2.8cm}{20220815_110341.jpg}
   \tagline{Computational Biologist}
   #+end_export

** Personal Info :ignore:
   #+begin_export latex
   \personalinfo{
    %%  \homepage{www.github.com/tuh8888}
     \email{pielkekid@gmail.com}
     \phone{720 209 6249}
     \location{Denver, CO}
     \github{https://www.github.com/tuh8888}
     \linkedin{https://www.linkedin.com/in/tuh8888}
   %%   \driving{US Driving Licence
     }
   }
   \makecvheader
   #+end_export

* CV Column 1 :ignore:
  #+begin_export latex
  \begin{paracol}{1}
  #+end_export
** Personal Statement                                       :ignore:noexport:
*** General                                       :ignore:
    #+begin_export latex
     \begin{quote}
     ``I am a Computational Bioscience graduate interested in developing software for artificial intelligence, health informatics, and game development. My work includes developing novel algorithms for symbolic AI and natural language processing. As a polyglot programmer, I enjoy turning difficult problems for people into easy solutions for computers.''
     \end{quote}
    #+end_export
*** Reify Health                         :ignore:noexport:
    #+begin_export latex
     \begin{quote}
     ``I am a Computational Bioscience graduate interested in developing software for healthcare, bioinformatics, and clinical applications. My work has included developing novel algorithms for symbolic AI and natural language processing. I am a polyglot programmer who enjoys turning difficult problems for people into easy solutions for computers.''
     \end{quote}
    #+end_export
** Experience
*** PhD Researcher :ignore:
    {{{cvevent(Computational Biologist, University of Colorado\, Anschutz Medical Campus, Aug 2016 -- Aug 2022, Aurora\, CO)}}}

    - Managed interconnected computational projects written in {{{cvtag(Python)}}}, {{{cvtag(Java)}}}, and {{{cvtag(Clojure)}}} across 4+ teams through consistent communication and leadership
    - Produced 6 publications, 4 dataset releases, and 5 package releases.
    - Developed interpretable, symbolic {{{cvtag(Artificial Intelligence)}}}, {{{cvtag(Machine Learning)}}}, and {{{cvtag(Natural Language Processing)}}} methods for identifying drug-targets in text and performing inductive reasoning about drug-disease mechanisms using a {{{cvtag(Knowledge Graph)}}} constructed from 10 biomedical ontologies and 10 databases containing 1 trillion triples.
*** IEEE Undergraduate Grant                                         :ignore:

    {{{par-div}}}

    {{{cvevent(IEEE Undergraduate Grant, University of Colorado\, Boulder, Aug 2015 -- May 2016, Boulder\, CO)}}}

    - Used an Aho-Corrasick automata representation  of CRISPR-Cas9 binding sites implemented in {{{cvtag(Python)}}} and {{{cvtag(MATLAB)}}} to reduce the complexity of the estimation of binding coverage from O(4^n) (4^{\text{3 billion}}) combinations to a O(1) (constant time statistical approximation when n is large).

*** Cancer Center Summer Fellow                                      :ignore:

    {{{par-div}}}

    {{{cvevent(Cancer Center Summer Fellow, University of Colorado\, Anschutz Medical Campus, Jun 2015 -- Aug 2015, Aurora\, CO)}}}

    - Optimized and evaluated a drug-efficacy scoring algorithm which incorporates multi-omic data including cancer genomes and drug-target profiles. Communicated results with domain experts using heat-map visualizations of kinase scores for selected cancer subtypes.

** Projects
*** LeSS                                                             :ignore:

    {{{cvevent(Schematization of biological mechanisms from structural\, semantic\, and causal properties,,2017 -- 2022,)}}}

    - Conceptualized and tested algorithmic approaches in {{{cvtag(Clojure)}}} and {{{cvtag(Python)}}} for extending analogical reasoning of complex networks representing biological knowledge. Merged and harmonized large biomedical knowledge graphs represented in {{{cvtag(RDF)}}}, {{{cvtag(Datomic)}}}, and {{{cvtag(SQL)}}} formats.

*** Knowtator                                                        :ignore:

    {{{par-div}}}

    {{{cvevent(Knowtator: Concept/relation annotation for Protégé,,2016--2022,)}}}

    - Deployed a WYSIWYG {{{cvtag(Java)}}} plugin for ontology development and text annotation that includes interactive graph visualization for textual features. It was used to annotate over 100k concept and relation annotations. Later became a {{{cvtag(Clojurescript)}}} {{{cvtag(web application)}}}. {{{cvtag(CI/CD)}}}: Incorporated user feedback  in several feature updates.

    # {{{cvtag(Semantic web)}}}
    # {{{cvtag(UX/GUI)}}}
    # {{{cvtag(Ontology)}}}

*** Dep2Rel                                                          :ignore:

    {{{par-div}}}

    {{{cvevent(Bootstrapped relation extraction using word embeddings and dependency paths,,2016--2019,)}}}

    - Automated relation extraction by implementing a novel bootstrapping approach in {{{cvtag(Clojure)}}} that creates human-interpretable syntax patterns from dependency paths and word embeddings. Performance optimized with GPU accelerated matrix operations. Improved precision for relation extraction for drug-targets from biomedical texts by 10%.

    # {{{cvtag(Natural language processing)}}}
    # {{{cvtag(Semantic web)}}}

** Publications                                                    :noexport:
   #+begin_export latex
\nocite{*}
% \printbibliography[heading=pubtype,title={\printinfo{\faBook}{Books}},type=book]
% \divider
% \printbibliography[heading=pubtype,title={\printinfo{\faFile*[regular]}{Journal Articles}},type=article]
% \divider
\printbibliography[heading=none]
#+end_export

** Newpage                                                  :ignore:noexport:
   {{{new-page}}}

** Projects (Cont.)                                                :noexport:

** A day of my life :noexport:
   # #+begin_export latex
   # % \medskip

   # % \cvsection{A Day of My Life}

   # % % Adapted from @Jake's answer from http://tex.stackexchange.com/a/82729/226
   # % % \wheelchart{outer radius}{inner radius}{
   # % % comma-separated list of value/text width/color/detail}
   # % \wheelchart{1.5cm}{0.5cm}{%
   # %   6/8em/accent!30/{Sleep,\\beautiful sleep},
   # %   3/8em/accent!40/Hopeful novelist by night,
   # %   8/8em/accent!60/Daytime job,
   # %   2/10em/accent/Sports and relaxation,
   # %   5/6em/accent!20/Spending time with family
   # % }

   # % % use ONLY \newpage if you want to force a page break for
   # % % ONLY the current column
   # % \newpage
   # #+end_export

** Newpage :ignore:noexport:
   {{{new-page}}}

** Volunteering                                                    :noexport:
*** FARSCOPE Course Rep :ignore:
    {{{cvevent(Cohort Representative, FARSCOPE CDT, Sept 2018 - Ongoing, Bristol\, UK)}}}
    # - I represent myself and fellow CDT students in management meetings where I communicate ideas and information between students and management.
    - Represent myself and my CDT peers in management meetings.
    - Communicate information between students and management.

    {{{cvtag(Communication)}}}
    {{{cvtag(Interpersonal Skills)}}}

    {{{par-div}}}

*** Code Club :ignore:
    {{{cvevent(Club Leader, Code Club, Dec 2017 - April 2018, Junction 3 Library\, Bristol \, UK)}}}

    # - I collaborated with [[https://codeclub.org/en/][Code Club]] and Bristol Libraries to set up and run a Code Club for young people aged 9-13.
    # - Demonstrating my abi involved organising,  planning lessons and teaching
    - Set up (and then ran) a [[https://codeclub.org/en/][Code Club]] for children aged 9-13.
    - Led the organisation, planning and teaching of weekly lessons.
    - Planned lessons to engage children by making coding fun.
    - Extremely rewarding and reinforced my love for teaching.
    # - @ Junction 3 Library in Easton, Bristol.

    {{{cvtag(Leadership)}}}
    {{{cvtag(Teaching)}}}
    {{{cvtag(Communication)}}}
    {{{cvtag(Active listening)}}}

*** Drivetrain :ignore:noexport:
    {{{par-div}}}

    {{{cvevent(Technical Lead (Drivetrain), Formula Student, Jan 2015 - Jan 2016, Bristol\, UK)}}}

    Each year, as part of Formula Student, students design, build and race a single seat race car.
    - Finished 2nd in the National Class 2 competition in 2013/2014, I was then selected as the Drivetrain lead.
    - This role improved my communication skills as I was leading weekly presentations.
    - I developed my leadership skills through setting realistic objectives, effectively allocating work to the appropriate team members and monitoring outcomes.

    {{{cvtag(Teamwork)}}}
    {{{cvtag(Leadership)}}}
    {{{cvtag(Time Management)}}}

*** Snowboard Captain :ignore:noexport:
    {{{par-div}}}

    {{{cvevent(Snowboard Captain, University of Bristol Snowsports Club, Jan 2014 - Sept 2015, Bristol\, UK)}}}

    - Organised multiple weekly training sessions, demonstrating my ability to plan and run events smoothly.
    - Negotiated competitive prices for a growing member base within an inherently expensive sport.
    - Responsible for aiding the smooth running of the club and helping to organise the annual university ski trip, with circa 1500 participants, working under pressure to manage people in high stress situations.
    - Awarded the ‘Team of the Year’ award and full colours for my performances and contributions to the sport.

    {{{cvtag(Teamwork)}}}
    {{{cvtag(Leadership)}}}
    {{{cvtag(Time Management)}}}

* CV Column 2                                                        :ignore:
  # Switch to the right column - will automatically move to the next page.

** Education
*** PhD in CPBS                                             :ignore:noexport:
    {{{cvevent(PhD Candidate in Computational Biosciences, University of Colorado\, Anschutz Medical Campus, 2016 -- Ongoing, Aurora\, Co)}}}

    {{{par-div}}}

*** Master of Science                                                :ignore:

{{{cvevent(Master of Science in Computational Bioscience, University of Colorado\, Anschutz Medical Campus, 2016 --- 2022, Aurora\, CO)}}}
*** Master of Science with footnote                         :ignore:noexport:
    {{{par-div}}}
    #+BEGIN_EXPORT latex
    \cvevent{\footnote{Awarded if PhD is not completed.} MS in Biomedical Sciences}{University of Colorado\, Anschutz Medical Campus}{2016 --- 2022}{Aurora\, CO}
    #+END_EXPORT

*** Bachelor of Science                                              :ignore:
    {{{par-div}}}

    {{{cvevent(Bachelor of Science in Applied Mathematics, University of Colorado, 2013 -- 2016,Boulder\, CO)}}}
    - Minor in Computer Science
    - Minor in Biochemistry
    # - First Class Honours \\


   {{{new-page}}}

** Skills
- {{{accent(Python)}}}
- {{{accent(Java)}}}
- {{{accent(JavaScript)}}}
- {{{accent(Clojure)}}}
- {{{accent(AWS)}}}
- {{{accent(Kubernetes)}}}
- {{{accent(Creativity)}}}
- {{{accent(Organization)}}}
- {{{accent(SDLC)}}}
- {{{accent(CI/CD)}}}
- {{{accent(Natural language processing)}}}
- {{{accent(Statistics)}}}
- {{{accent(Machine learning)}}}
- {{{accent(Semantic web)}}}
- {{{accent(Artificial intelligence)}}}
- {{{accent(Databases)}}}
- {{{accent(Communication)}}}
- {{{accent(Teamwork)}}}

** Note                                                            :noexport:
   References available upon request. Please see my GitHub page (@tuh8888) for my software projects as well as my contributions to various open-source projects.

** Newpage :ignore:noexport:
   #+BEGIN_EXPORT latex
   \newpage
   #+END_EXPORT

** My Life Philosophy :noexport:
   #+begin_export latex
   % \begin{quote}
   % ``Something smart or heartfelt, preferably in one sentence.''
   % \end{quote}
   #+end_export

** Achievements :noexport:
   {{{cvachievement(\faTrophy, Full Sporting Colours, Awarded full colours for outstanding achievements in snowboarding. Multiple gold medals in British University Snowboard Championships.)}}}

   {{{divider}}}

   {{{cvachievement(\faCertificate, Starting To Teach, Established myself as a confident\, enthusiastic and effective teacher who is able to engage\, encourage and develop students' learning.)}}}

   {{{divider}}}

   {{{cvachievement(\faTrophy,Bristol Plus Award, For undertaking a wide range of tasks to further enhance student skills - only 700 out of 23\,000 achieved this award per annum.)}}}

   {{{divider}}}

   {{{cvachievement(\faCertificate, Mary Jones Prize for Mathematics, For outstanding achievements in A Level mathematics @ Ripon Grammar School)}}}

   {{{divider}}}

   {{{cvachievement(\faTrophy, The Duke of Edinburgh's Award, Bronze/Silver/Gold)}}}

** Languages :noexport:
   #+begin_export latex
   % \cvsection{Languages}

   % \cvskill{English}{5}
   % \divider

   % \cvskill{Spanish}{4}
   % \divider

   % \cvskill{German}{3}

   % %% Yeah I didn't spend too much time making all the
   % %% spacing consistent... sorry. Use \smallskip, \medskip,
   % %% \bigskip, \vpsace etc to make ajustments.
   % \medskip
   #+end_export

   \newpage
** References                                                      :noexport:
   #+begin_export latex
   % \cvref{name}{email}{mailing address}
   \cvref{Dr.\ Lawrence Hunter}{University of Colorado}{lawrence.hunter@cuanschutz.edu}
   % {Address Line 1\\Address line 2}
   #+end_export
   - Thesis advisor
   {{{divider}}}
   #+begin_export latex
   \cvref{Dr.\ James Costello}{University of Colorado}{james.costello@cuanschutz.edu}
   % {Address Line 1\\Address line 2}
   #+end_export
   - Committee chair

* Back Matter :ignore:
  #+begin_export latex
  \end{paracol}
  \end{document}
  #+end_export

  # Local Variables:
  # org-cite-global-bibliography: nil
  # End:
